#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
set -euo pipefail

# TODO: Description

# -----------------------------------------------------------------------------

# Attest that it's run from inside tmux.
if [ "$1" != "--!" ]; then
	echo "$0: this script isn't meant to be run directly"
	exit 1
fi

# Get the tty of the active pane.
ACTIVE_PANE="$(tmux display-message -p "#{pane_id}")"

# Run the command.
#   -c to set the pwd to the same as the active pane.
#   -e to tell the new pane which pane created it.
tmux "${@:2}" -c "#{pane_current_path}" -e "INIT_TMUX_PANE_CREATOR=${ACTIVE_PANE}" \
	|| exit $?

