#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles

# This script will attempt to save the editor in the current tmux pane.

USE_VI_F6_SAVE=true

# -----------------------------------------------------------------------------
set -eo pipefail

# Attest that it's run from inside tmux.
if [ "$1" != "--!" ]; then
	echo "$0: this script isn't meant to be run directly"
	exit 1
fi

# We pass the socket and pane ID through the run-shell command. 
export TMUX="$2"
export TMUX_PANE="$3"

# Try to save based on the current command.
PANE_CURRENT_COMMAND="$4"
case "$PANE_CURRENT_COMMAND" in
	vi|vim|nvim|neovim)
		if "$USE_VI_F6_SAVE"; then
			tmux send-keys F6
		else
			tmux send-keys C-c
			sleep 0.1
			tmux send-keys :w Enter
		fi
		exit 0
		;;

	*)
		tmux display-message "Don't know how to save '$PANE_CURRENT_COMMAND'"
		;;
esac

