#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles

# tmux-util-open-url
# Usage: tmux-util-open-url URL
#
# This utility script will open a URL using the system web browser.
# If not possible, the script will exit 1 and print an error message.

# -----------------------------------------------------------------------------
set -euo pipefail
HERE="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# -----------------------------------------------------------------------------

case "$(uname -s)" in

	# MacOS: open command
	"Darwin")
		open -- "$1"
		exit 0;;
	
	# Others:
	*)
		if command -v xdg-open &>/dev/null; then
			xdg-open -- "$1"
			exit 0
		fi

		echo "No program to open URL: $1"
		exit 1;;
esac

