#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# =============================================================================
#
# Summary
# -------
#
#   This script will attempt to copy selected text (or enter copy mode) in the 
#   foreground program. If the foreground program cannot be detected or does
#   not have a supported integration, tmux's copy mode will be used instead.
#
#   Supported programs:
#
#    - vim (and neovim)
#
# Arguments
# ---------
#
#   $1  [--config=CONFIG_FILE]    # Optional config file.
#   $1  "--!"                     # Attestation constant.
#   $2  TMUX_SOCKET               # Path to the tmux socket.
#   $3  TMUX_PANE                 # The target tmux pane.
#   $4  TMUX_WINDOW               # The target tmux window.
#   $5  TMUX_CURRENT_COMMAND      # The current command running in the pane.
#   $6  TMUX_CURRENT_TITLE        # The current title of the pane.
#
# How it's used in my-dotfiles
# ----------------------------
#
#   This script is activated by the key sequence sent from Alacritty's Cmd+C
#   binding, through tmux.
#
# =============================================================================
set -euo pipefail

INTEGRATION_JOB_SELECTOR_FISH_BINDING=('C-S-F12' 'j')

if [[ "$1" =~ --config=(.*) ]]; then
	source "${BASH_REMATCH[1]}"
	shift
fi


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

# Attest that it's run from inside tmux.
if [ "$1" != "--!" ]; then
	echo "$0: this script isn't meant to be run directly"
	exit 1
fi

# Collect arguments.
export TMUX="$2"
export TMUX_PANE="$3"
TMUX_WINDOW="$4"
PANE_CURRENT_COMMAND="$5"
PANE_CURRENT_TITLE="$6"
PANE_COMMAND_NAME="$(basename -- "$PANE_CURRENT_COMMAND")"
TITLE_COMMAND_NAME="$(basename -- "$(cut -d' ' -f1 <<< "$PANE_CURRENT_TITLE")")"

# In a supported program? Copy using the program's features.
for command_name in "$PANE_COMMAND_NAME" "$TITLE_COMMAND_NAME"; do
case "$command_name" in
	fish)
		if [[ "${#INTEGRATION_COPY_VIM_BINDING[@]}" -ne 0 ]]; then
			tmux send-keys -t "$TMUX_PANE" "${INTEGRATION_JOB_SELECTOR_FISH_BINDING[@]}"
			exit 0
		fi
		break;;
esac
done

# Unsupported.
tmux display-message "Don't know how to select jobs in '$PANE_CURRENT_COMMAND'"
exit 0

