#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# =============================================================================
#
# Summary
# -------
#
#   This script will copy text from the standard input stream into the
#   system clipboard.
#
#   Supported platforms:
#
#    - macOS (via pbcopy)
#    - linux (via xclip)
#
# Arguments
# ---------
#
#   None
#
# How it's used in my-dotfiles
# ----------------------------
#
#   Currently unused.
#
# =============================================================================
set -euo pipefail
HERE="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Try to copy STDIN into a clipboard.
if command -v pbcopy &>/dev/null; then
	pbcopy
elif command -v xclip &>/dev/null; then
	xclip -in -selection clipboard
else
	echo "Unsupported system." 1>&2
	exit 1
fi

