#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles

# This script will enter copy mode.

USE_VIM_VISUAL_MODE_BINDING=true

# -----------------------------------------------------------------------------
set -eo pipefail

# Attest that it's run from inside tmux.
if [ "$1" != "--!" ]; then
	echo "$0: this script isn't meant to be run directly"
	exit 1
fi

# We pass the socket and pane ID through the run-shell command. 
export TMUX="$2"
export TMUX_PANE="$3"
export TMUX_WINDOW="$4"

# In a supported progrma? Copy using the program's features.
PANE_CURRENT_COMMAND="$5"
PANE_CURRENT_COMMAND_NAME="$(basename -- "$PANE_CURRENT_COMMAND")"
case "$PANE_CURRENT_COMMAND_NAME" in
	vi|vim|nvim|neovim)
		if "$USE_VIM_VISUAL_MODE_BINDING"; then
			tmux send-keys -t "$TMUX_PANE" F5
			exit 0
		fi
		;;
esac

# Just enable tmux's copy mode.
tmux setw -t "$TMUX_WINDOW" mode-keys vi
tmux copy-mode -t "$TMUX_PANE"
exit 0

