#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles

# tmux-util-clipboard-copy
# Usage: echo "text" | tmux-util-clipboard-copy
#
# This utility script will copy its input into the system clipboard.

# -----------------------------------------------------------------------------
set -euo pipefail
HERE="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# -----------------------------------------------------------------------------

# Try to copy STDIN into a clipboard.
if command -v pbcopy &>/dev/null; then
	pbcopy
elif command -v xclip &>/dev/null; then
	xclip -in -selection clipboard
else
	echo "Unsupported system." 1>&2
	exit 1
fi

