#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# =============================================================================
# 
# Summary
# -------
#
#   This script will try to open a file in the foreground program.
#   
#   Supported programs:
#
#    - fish    # For changing directories.
#
# Arguments
# ---------
#
#   $1  [--config=CONFIG_FILE]    # Optional config file.
#   $1  "--!"                     # Attestation constant.
#   $2  TMUX_SOCKET               # Path to the tmux socket.
#   $3  TMUX_PANE                 # The target tmux pane.
#   $4  TMUX_CURRENT_COMMAND      # The current command running in the pane.
#   $5  TMUX_CURRENT_TITLE        # The current title of the pane.
#
# How it's used in my-dotfiles
# ----------------------------
#
#   This script is activated by the key sequence sent from Alacritty's Cmd+O
#   binding, through tmux.
#
# =============================================================================
set -euo pipefail

INTEGRATION_OPEN_FISH_BINDING=("C-S-F12" "o")
INTEGRATION_OPEN_VIM_BINDING=("C-M-F12" "o")

if [[ "$1" =~ --config=(.*) ]]; then
	source "${BASH_REMATCH[1]}"
	shift
fi


# -----------------------------------------------------------------------------

# Attest that it's run from inside tmux.
if [ "$1" != "--!" ]; then
	echo "$0: this script isn't meant to be run directly"
	exit 1
fi

# Collect arguments.
export TMUX="$2"
export TMUX_PANE="$3"
PANE_CURRENT_COMMAND="$4"
PANE_CURRENT_TITLE="$5"
PANE_COMMAND_NAME="$(basename -- "$PANE_CURRENT_COMMAND")"
TITLE_COMMAND_NAME="$(basename -- "$(cut -d' ' -f1 <<< "$PANE_CURRENT_TITLE")")"

# In a supported program? Open using the program's features.
for command_name in "$PANE_COMMAND_NAME" "$TITLE_COMMAND_NAME"; do
case "$command_name" in
	fish)
		if [[ "${#INTEGRATION_OPEN_FISH_BINDING[@]}" -ne 0 ]]; then
			tmux send-keys -t "$TMUX_PANE" "${INTEGRATION_OPEN_FISH_BINDING[@]}"
			exit 0
		fi
		break;;
	
	vi|vim|nvim|neovim)
		if [[ "${#INTEGRATION_OPEN_VIM_BINDING[@]}" -ne 0 ]]; then
			tmux send-keys -t "$TMUX_PANE" "${INTEGRATION_OPEN_VIM_BINDING[@]}"
			exit 0
		fi
		break;;
esac
done

# Unsupported.
tmux display-message "Don't know how to open in '$PANE_CURRENT_COMMAND'"
exit 0

