#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# =============================================================================
#
# Summary
# -------
#
#   This script will try to open a URL in a GUI program.
#
#   Supported platforms:
#
#    - macOS (via open)
#    - Linux (via xdg-open)
#
# Arguments
# ---------
#
#   $1  URL    # The URL to open.
#
# How it's used in my-dotfiles
# ----------------------------
#
#   This script is involved by the `~/.local/libexec/tmux-open-link` script
#   when it finds a URL to open. Indirectly, it's activated when the user
#   control-clicks on a link in tmux.
#
# =============================================================================
set -euo pipefail
HERE="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

case "$(uname -s)" in

	# MacOS: open command
	"Darwin")
		open -- "$1"
		exit 0;;
	
	# Others:
	*)
		if command -v xdg-open &>/dev/null; then
			xdg-open -- "$1"
			exit 0
		fi

		echo "No program to open URL: $1"
		exit 1;;

esac

