#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2021 eth-p
# Repository: https://github.com/eth-p/my-dotfiles

# This script will attempt to open a file/directory in the current tmux pane.

USE_FISH_INTEGRATIONS=true

# -----------------------------------------------------------------------------
set -eo pipefail

# Attest that it's run from inside tmux.
if [ "$1" != "--!" ]; then
	echo "$0: this script isn't meant to be run directly"
	exit 1
fi

# We pass the socket and pane ID through the run-shell command. 
export TMUX="$2"
export TMUX_PANE="$3"

# Try to open based on the current command.
PANE_CURRENT_COMMAND="$4"
PANE_CURRENT_COMMAND_NAME="$(basename -- "$PANE_CURRENT_COMMAND")"
case "$PANE_CURRENT_COMMAND_NAME" in
	fish)
		if "$USE_FISH_INTEGRATIONS"; then
			tmux send-keys -t "$TMUX_PANE" 'C-F12' 'e' 'c'
			exit 0
		fi
		;;
	
	vi|vim|nvim|neovim)
		: # TODO
		;;
esac

# Unsupported.
tmux display-message "Don't know how to open in '$PANE_CURRENT_COMMAND'"
exit 0

