#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2025 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# ==============================================================================
set -euo pipefail
cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."

source "lib/bash/bootstrap-utils.sh"

# ------------------------------------------------------------------------------
@section "installing Nix package manager"

if command -v nix &> /dev/null; then
	@notice "nix is already installed"

else
	tempdir="$(mktemp -d)"
	@cleanup-file "$tempdir"

	curl -sSfL https://nixos.org/nix/install -o "$tempdir/nix-install.sh"
	"$tempdir/nix-install.sh" --daemon
	sudo bash -c 'echo "experimental-features = nix-command flakes" >>/etc/nix/nix.conf'
fi

# ------------------------------------------------------------------------------
@section "bootstrapping configuration"

sys_arch="$(uname -m | sed 's/arm64/aarch64/')"
sys_os="$(uname -s | tr '[:upper:]' '[:lower:]')"

@create-and-overwrite bootstrap.json << EOF
{
  "username": "$(id -un)",
  "homeDirectory": "${HOME}",
  "system": "${sys_arch}-${sys_os}"
}
EOF

@create-if-missing config.nix << EOF
{ lib, pkgs, config, ... }:
{
  my-dotfiles.global = {
    nerdfonts = false;
    theme     = "dark";
  };

  # Fix locale errors when using programs installed through Nix. 
# home.language.base = "C.UTF-8";
# home.sessionVariables.LANG = "C.UTF-8";

  # Put device-specific config here.

  programs.git = {
    userName = "$(id -un)";
    userEmail = "$(id -un)@$(hostname)";
  };
}
EOF

@create-if-missing config.profile <<< "minimal"

# ------------------------------------------------------------------------------
@section "installing utilities"

@link-if-missing "${HOME}/.local/bin/my-dotfiles" "$(pwd)/scripts/my-dotfiles"

# ------------------------------------------------------------------------------
@section "installing configuration"

profile="$(cat config.profile)"
@notice "using profile '${profile}'"

nix shell 'home-manager' \
	--command 'home-manager' switch \
	--flake "path:.#${profile}"
