#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2025 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# ==============================================================================
set -euo pipefail
cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."

if [[ "$#" -lt 1 ]]; then
	profile="$(cat config.profile)"
else
	profile="$1"
	printf "%s\n" "$profile" > config.profile
fi

# If home-manager is not installed, shim it with nix shell.
if ! command -v home-manager &> /dev/null; then
	home-manager() {
		nix shell 'home-manager' --command 'home-manager' "$@" || return $?
	}
fi

# Run home-manager.
home-manager switch --flake "path:.#${profile}"

# Delete neovim's Luajit cache if it gets too large.
if [[ "$(du -k "$HOME/.cache/nvim/luac" | awk '{ print $1 }')" -gt 65536 ]]; then
	find "$HOME/.cache/nvim/luac" -iname "%2fnix%2fstore%2f*.luac" | xargs rm
fi
