#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2025 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# ==============================================================================
set -euo pipefail
cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."

if [[ "$#" -lt 1 ]]; then
	profile="$(cat config.profile)"
else
	profile="$1"
	printf "%s\n" "$profile" > config.profile
fi

nix shell 'home-manager' \
	--command 'home-manager' switch \
	--flake "path:.#${profile}"
