#!/usr/bin/env bash
# my-dotfiles | Copyright (C) 2023-2024 eth-p
# Repository: https://github.com/eth-p/my-dotfiles
# =============================================================================
#
# Summary
# -------
#
#   Sends the Google Chrome flatpak process a friendly SIGTERM to ask it
#   to close cleanly.
#
# How it's used on my Steam Deck
# ------------------------------
#
#   As Plasma shutdown/logout hook so that Chrome can exit cleanly
#   and not complain about an unexpected shutdown when started up next.
#
# =============================================================================
set -euo pipefail
FLATPAK_ID="com.google.Chrome"

# Check if Chrome is running.
if ! flatpak ps --columns=application | grep -xqF "$FLATPAK_ID"; then
    echo "Chrome is not running." 1>&2
    exit 0
fi

# Find the initial `chrome` process.
#
# This process is the manager for the subprocesses used by its multiprocess
# architecture. It will interpret a SIGINT as a quit request, and run the
# appropriate IPC calls to end all the other processes.
PID="$(/usr/bin/pkill --oldest --signal 0 --echo -f /app/extra/chrome | grep -Eo '[0-9]+')"
kill -INT "$PID"
echo "Asking Chrome (pid $PID) to terminate."

# Wait for chrome to exit.
# Give it 15 seconds before forcefully killing it.
for attempt in {0..15000}; do
    if ! kill -0 "$PID" &>/dev/null; then
        break
    fi

    sleep 0.01
done

# If it's not dead yet, kill it forcefully.
# We don't want to stall the logout process any longer.
if kill -0 "$PID" &>/dev/null; then
    echo "Forcing Chrome (pid $PID) to terminate."
    kill -KILL "$PID"
    sleep 1
    flatpak kill com.google.Chrome
fi
